# Generated by Django 3.0.6 on 2020-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='audio')),
                ('genre', models.CharField(max_length=15)),
                ('album_art', models.ImageField(default='default.jpg', upload_to='album_art')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
