# Generated by Django 3.0.6 on 2020-05-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boomx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_art',
            new_name='image',
        ),
    ]
