# Generated by Django 3.0.6 on 2020-05-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomx', '0002_auto_20200528_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
    ]
