# Generated by Django 3.0.6 on 2020-05-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomx', '0003_auto_20200529_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(upload_to='audio'),
        ),
    ]
